services:

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: